/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:645a8738-922b-485c-9c5a-005d59d9c9f1",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_xGY4xRLEm",
    "aws_user_pools_web_client_id": "2a7b7rf849fbm24j4vht3t8trq",
    "oauth": {
        "domain": "er65ffycg4fl-develop.auth.eu-north-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "instaphotoapp://",
        "redirectSignOut": "instaphotoapp://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ck6lshrwrzew5k3mbikhbcqfjm.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3pleuy22cvev5bolp47qnta7pa",
    "aws_user_files_s3_bucket": "picgramphotos-media113135-develop",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
